In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)

In [10]:
customers = pd.read_csv(r"C:\Users\borde\OneDrive\Desktop\fork\week0\data\ecommerce\orders.csv")
orders = pd.read_csv(r"C:\Users\borde\OneDrive\Desktop\fork\week0\data\ecommerce\orders.csv")
payments = pd.read_csv(r"C:\Users\borde\OneDrive\Desktop\fork\week0\data\ecommerce\payments.csv")
products = pd.read_csv(r"C:\Users\borde\OneDrive\Desktop\fork\week0\data\ecommerce\products.csv")

In [9]:
customers.head()

,OrderID,CustomerID,OrderDate,ProductID,Quantity,Discount,PaymentMethod,Status
0,500001,103695,2025-08-28,2003,4.0,0.1,Gateway,Completed
1,500002,107935,2024-05-31,2014,1.0,0.1,Wallet,Completed
2,500003,105141,2025-08-10,2002,1.0,0.2,CardToCard,Completed
3,500004,108780,2024-10-11,2012,1.0,0.1,Gateway,Completed
4,500005,101187,2024-02-19,2008,2.0,0.0,Gateway,Completed

In [11]:
orders.head()

,OrderID,CustomerID,OrderDate,ProductID,Quantity,Discount,PaymentMethod,Status
0,500001,103695,2025-08-28,2003,4.0,0.1,Gateway,Completed
1,500002,107935,2024-05-31,2014,1.0,0.1,Wallet,Completed
2,500003,105141,2025-08-10,2002,1.0,0.2,CardToCard,Completed
3,500004,108780,2024-10-11,2012,1.0,0.1,Gateway,Completed
4,500005,101187,2024-02-19,2008,2.0,0.0,Gateway,Completed

In [12]:
payments.head()

   PaymentID  OrderID PaymentDate PaymentStatus
0     800001   500001  2025-08-28          Paid
1     800002   500002  2024-05-31          Paid
2     800003   500003  2025-08-10          Paid
3     800004   500004  2024-10-11          Paid
4     800005   500005  2024-02-19          Paid

In [13]:
products.head()

   ProductID          ProductName     Category  UnitPrice
0       2001       Wireless Mouse  Electronics       18.0
1       2002  Mechanical Keyboard  Electronics       62.0
2       2003          USB-C Cable  Accessories        9.0
3       2004           Power Bank  Electronics       35.0
4       2005         Laptop Stand  Accessories       28.0